# -*- coding: utf-8 -*-
"""ExpediaPostings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6kJPicaGy4KGsb-GrS5e9K-zb67tDri
"""

# -------------------------------------------------------------
# EXPEDIA JOB POSTING AUTHENTICITY PREDICTION PROJECT
# -------------------------------------------------------------
# Goal: Build a machine learning model to predict whether a job posting is real or fake
# Evaluation Metric: Accuracy
# Deliverables: "submissions.csv" with columns [id, is_authentic]
# -------------------------------------------------------------

# 1. Import Libraries
# -------------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV

# -------------------------------------------------------------
# 2. Load Data
# -------------------------------------------------------------
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)
print(train.head())

# -------------------------------------------------------------
# 3. Handle Missing Values and Combine Text Features
# -------------------------------------------------------------
text_features = [
    "title", "location", "department", "industry",
    "employment_type", "required_education", "salary_range"
]

for col in text_features:
    train[col] = train[col].fillna("Unknown")
    test[col] = test[col].fillna("Unknown")

# Combine all text columns into one "combined_text" column
train["combined_text"] = train[text_features].apply(lambda x: " ".join(x.astype(str)), axis=1)
test["combined_text"] = test[text_features].apply(lambda x: " ".join(x.astype(str)), axis=1)

# -------------------------------------------------------------
# 4. Convert Flag Columns to Numeric (0/1)
# -------------------------------------------------------------
for col in ["work_from_home", "company_logo", "screening_round", "required_experience"]:
    train[col] = (
        train[col]
        .astype(str)
        .str.lower()
        .map({'true': 1, 'yes': 1, '1': 1, 'false': 0, 'no': 0, '0': 0})
        .fillna(0)
        .astype(int)
    )
    test[col] = (
        test[col]
        .astype(str)
        .str.lower()
        .map({'true': 1, 'yes': 1, '1': 1, 'false': 0, 'no': 0, '0': 0})
        .fillna(0)
        .astype(int)
    )

# -------------------------------------------------------------
# 5. Feature Selection & Train-Test Split
# -------------------------------------------------------------
X = train[["combined_text", "work_from_home", "company_logo", "screening_round", "required_experience"]]
y = train["is_authentic"]

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 💡 Explanation:
# train_test_split splits our dataset into training and validation sets.
# 80% of data is used to train the model, 20% to evaluate performance.

# -------------------------------------------------------------
# 6. Build TF-IDF + RandomForest Pipeline
# -------------------------------------------------------------
tfidf = TfidfVectorizer(stop_words='english', max_features=5000, ngram_range=(1, 2))

preprocessor = ColumnTransformer(
    transformers=[
        ("text", tfidf, "combined_text"),
        ("num", "passthrough", ["work_from_home", "company_logo", "screening_round", "required_experience"])
    ]
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42, n_estimators=200, max_depth=20))
])

# -------------------------------------------------------------
# 7. Train and Evaluate Model
# -------------------------------------------------------------
model.fit(X_train, y_train)
y_pred = model.predict(X_val)

accuracy = accuracy_score(y_val, y_pred)
print(f"\nValidation Accuracy: {accuracy:.4f}\n")
print("Classification Report:\n", classification_report(y_val, y_pred))

# -------------------------------------------------------------
# 8. Feature Importance Visualization
# -------------------------------------------------------------
# Extract feature importances from the Random Forest
feature_names = (
    model.named_steps["preprocessor"]
    .transformers_[0][1]
    .get_feature_names_out(["combined_text"])
)

# Add numeric feature names manually
feature_names = np.append(
    feature_names, ["work_from_home", "company_logo", "screening_round", "required_experience"]
)

importances = model.named_steps["classifier"].feature_importances_
indices = np.argsort(importances)[::-1]

top_n = 20
top_features = feature_names[indices][:top_n]
top_importances = importances[indices][:top_n]

colors = sns.color_palette("viridis", len(top_features))

# Plot top 20 important features
plt.figure(figsize=(10, 6))
sns.barplot(x=top_importances, y=top_features,palette = colors)
plt.title("Top 20 Most Important Features for Predicting Job Authenticity")
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

# Create and save a summary table
feature_importance_table = pd.DataFrame({
    "Feature": top_features,
    "Importance_Score": top_importances
})
feature_importance_table.to_csv("top_features_summary.csv", index=False)
print("\nSaved 'top_features_summary.csv'")

# -------------------------------------------------------------
# 9. Predict on Test Data
# -------------------------------------------------------------
test_predictions = model.predict(test)
submission = pd.DataFrame({
    "id": test["id"],
    "is_authentic": test_predictions
})

submission.to_csv("submissions.csv", index=False)
print("\nSubmission file 'submissions.csv' created")